
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 LP.glb --transform
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('/models/LP-transformed.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group position={[0, 0.12, 0,]} >
<T.Mesh geometry={gltf.nodes.Circle001.geometry} material={gltf.materials['Material.001']} />
<T.Mesh geometry={gltf.nodes.Circle001_1.geometry} material={gltf.materials['Material.002']} />
<T.Mesh geometry={gltf.nodes.Circle001_2.geometry} material={gltf.materials['Material.003']} />

</T.Group>

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	